In [112]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df=pd.read_csv("C:\\Users\\Saksham Kaushik\\Downloads\\titanic\\train.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.shape

(891, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


## Handling Null Values

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [9]:
df['Age'].mean()

np.float64(29.69911764705882)

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [11]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [12]:
df['Cabin'].mode()

0        B96 B98
1    C23 C25 C27
2             G6
Name: Cabin, dtype: object

In [13]:
df['Cabin'] = df.groupby('Survived')['Cabin'].transform(lambda x: x.fillna(x.mode()[0]))

In [14]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [15]:
df['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [16]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [17]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [18]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## Replacing Categorical values

In [22]:
df.replace({ 'Sex' : {'male':0 , 'female':1}},inplace=True)

C:\Users\Saksham Kaushik\AppData\Local\Temp\ipykernel_23892\665500005.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({ 'Sex' : {'male':0 , 'female':1}},inplace=True)


In [24]:
df.replace({'Embarked' : {'S':0,'C':1,'Q':2}}, inplace=True)

C:\Users\Saksham Kaushik\AppData\Local\Temp\ipykernel_23892\3100687122.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Embarked' : {'S':0,'C':1,'Q':2}}, inplace=True)


In [26]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.000000      1   
2                               Heikkinen, Miss. Laina    1  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.000000      1   
4                             Allen, Mr. William Henry    0  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    0  27.000000      0   
887                       Graham, Miss. Margaret Edith    1  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1  29.699118      1   
889                              Behr, Mr. Karl Howell    0  26.000000      0   
890                                Dooley, Mr. Patrick    0  32.000000      0   

     Parch            Ticket     Fare    Cabin  Embarked  
0        0         A/5 21171   7.2500     C124         0  
1        0          PC 17599  71.2833      C85         1  
2        0  STON/O2. 3101282   7.9250  B96 B98         0  
3        0            113803  53.1000     C123         0  
4        0            373450   8.0500     C124         0  
..     ...               ...      ...      ...       ...  
886      0            211536  13.0000     C124         0  
887      0            112053  30.0000      B42         0  
888      2        W./C. 6607  23.4500     C124         0  
889      0            111369  30.0000     C148         1  
890      0            370376   7.7500     C124         2  

[891 rows x 12 columns]

## Removing the unnecessary columns 

In [27]:
X = df.drop( columns = ['PassengerId' , 'Name' , 'Ticket','Cabin','Survived'] , axis=1)
Y = df['Survived']

In [28]:
print(X)

     Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    0  22.000000      1      0   7.2500         0
1         1    1  38.000000      1      0  71.2833         1
2         3    1  26.000000      0      0   7.9250         0
3         1    1  35.000000      1      0  53.1000         0
4         3    0  35.000000      0      0   8.0500         0
..      ...  ...        ...    ...    ...      ...       ...
886       2    0  27.000000      0      0  13.0000         0
887       1    1  19.000000      0      0  30.0000         0
888       3    1  29.699118      1      2  23.4500         0
889       1    0  26.000000      0      0  30.0000         1
890       3    0  32.000000      0      0   7.7500         2

[891 rows x 7 columns]


In [29]:
print(Y)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64


## Splitting Dataset

In [42]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=2)

In [43]:
print(X.shape,X_train.shape,X_test.shape)

(891, 7) (623, 7) (268, 7)


## Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression

In [97]:
model1 = LogisticRegression(max_iter=1000)
model1.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [98]:
model1_pred=model1.predict(X_test)
print(model1_pred)

[0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0
 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0
 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0
 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0
 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0
 1 0 0 0 1 0 0 0 1]


In [145]:
# score=accuracy_score(model1_pred,Y_test)
print("Accuracy of Logistic Regression: ",accuracy_score(model1_pred,Y_test))

Accuracy of Logistic Regression:  0.7947761194029851


In [101]:
confusion_matrix = confusion_matrix(Y_test, model1_pred)
print(confusion_matrix)
print(classification_report(model1_pred,Y_test))

[[143  17]
 [ 38  70]]
              precision    recall  f1-score   support

           0       0.89      0.79      0.84       181
           1       0.65      0.80      0.72        87

    accuracy                           0.79       268
   macro avg       0.77      0.80      0.78       268
weighted avg       0.81      0.79      0.80       268



## Decision Tree Classifier

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
model2 = DecisionTreeClassifier(random_state=42)
model2.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [143]:
model2_pred = model2.predict(X_test)

In [144]:
print("Decision Tree Accuracy:", accuracy_score(Y_test, model2_pred))
print(confusion_matrix(Y_test, model2_pred))
print(classification_report(Y_test, model2_pred))

Decision Tree Accuracy: 0.7686567164179104
[[134  26]
 [ 36  72]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.81       160
           1       0.73      0.67      0.70       108

    accuracy                           0.77       268
   macro avg       0.76      0.75      0.76       268
weighted avg       0.77      0.77      0.77       268



## Random Forest Classifier

In [106]:
from sklearn.ensemble import RandomForestClassifier

In [107]:
model3 = RandomForestClassifier(n_estimators=100, random_state=42)
model3.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [108]:
model3_pred = model3.predict(X_test)

In [113]:
print("Random Forest Accuracy:", accuracy_score(Y_test,model3_pred ))
print(confusion_matrix(Y_test,model3_pred))
print(classification_report(Y_test, model3_pred))

Random Forest Accuracy: 0.8022388059701493
[[146  14]
 [ 39  69]]
              precision    recall  f1-score   support

           0       0.79      0.91      0.85       160
           1       0.83      0.64      0.72       108

    accuracy                           0.80       268
   macro avg       0.81      0.78      0.78       268
weighted avg       0.81      0.80      0.80       268



## K-Nearest Neighbors (KNN)

In [114]:
from sklearn.neighbors import KNeighborsClassifier

In [116]:
model4 = KNeighborsClassifier(n_neighbors=5)  # You can tune n_neighbors
model4.fit(X_train, Y_train)

KNeighborsClassifier()

In [118]:
model4_pred = model4.predict(X_test)

In [119]:
print("K-Nearest Neighbors Accuracy:", accuracy_score(Y_test, model4_pred))
print(confusion_matrix(Y_test,model4_pred))
print(classification_report(Y_test, model4_pred))

K-Nearest Neighbors Accuracy: 0.6902985074626866
[[128  32]
 [ 51  57]]
              precision    recall  f1-score   support

           0       0.72      0.80      0.76       160
           1       0.64      0.53      0.58       108

    accuracy                           0.69       268
   macro avg       0.68      0.66      0.67       268
weighted avg       0.69      0.69      0.68       268



## Naive Bayes

In [120]:
from sklearn.naive_bayes import GaussianNB

In [121]:
model5 = GaussianNB()
model5.fit(X_train, Y_train)  

GaussianNB()

In [122]:
model5_pred = model5.predict(X_test)

In [123]:
print("Naive Bayes Accuracy:", accuracy_score(Y_test, model5_pred))
print(confusion_matrix(Y_test, model5_pred))
print(classification_report(Y_test, model5_pred))

Naive Bayes Accuracy: 0.7910447761194029
[[141  19]
 [ 37  71]]
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       160
           1       0.79      0.66      0.72       108

    accuracy                           0.79       268
   macro avg       0.79      0.77      0.78       268
weighted avg       0.79      0.79      0.79       268



## Support Vector Machine (SVM)

In [124]:
from sklearn.svm import SVC

In [125]:
model6 = SVC(kernel='rbf', C=1.0)  
model6.fit(X_train, Y_train)

SVC()

In [126]:
model6_pred = model6.predict(X_test)

In [127]:
print("SVM Accuracy:", accuracy_score(Y_test, model6_pred))
print(confusion_matrix(Y_test, model6_pred))
print(classification_report(Y_test, model6_pred))

SVM Accuracy: 0.6791044776119403
[[153   7]
 [ 79  29]]
              precision    recall  f1-score   support

           0       0.66      0.96      0.78       160
           1       0.81      0.27      0.40       108

    accuracy                           0.68       268
   macro avg       0.73      0.61      0.59       268
weighted avg       0.72      0.68      0.63       268



In [146]:
print("Accuracy of Logistic Regression: ",accuracy_score(model1_pred,Y_test))
print("Decision Tree Accuracy:", accuracy_score(Y_test, model2_pred))
print("Random Forest Accuracy:", accuracy_score(Y_test,model3_pred ))
print("K-Nearest Neighbors Accuracy:", accuracy_score(Y_test, model4_pred))
print("Naive Bayes Accuracy:", accuracy_score(Y_test, model5_pred))
print("SVM Accuracy:", accuracy_score(Y_test, model6_pred))

Accuracy of Logistic Regression:  0.7947761194029851
Decision Tree Accuracy: 0.7686567164179104
Random Forest Accuracy: 0.8022388059701493
K-Nearest Neighbors Accuracy: 0.6902985074626866
Naive Bayes Accuracy: 0.7910447761194029
SVM Accuracy: 0.6791044776119403


## Random Forest show highest accuracy 

## GridsearchCV for Hyperparameter tunning

In [128]:
from sklearn.model_selection import GridSearchCV

## For Logistic Regression

In [130]:
param_logreg = {
    'C': [0.1, 1, 10],
    'solver': ['liblinear', 'lbfgs']
}

grid_logreg = GridSearchCV(LogisticRegression(max_iter=1000), param_logreg, cv=5)
grid_logreg.fit(X_train, Y_train)

print("Best Logistic Regression:", grid_logreg.best_params_)
print("Accuracy:", accuracy_score(Y_test, grid_logreg.predict(X_test)))

Best Logistic Regression: {'C': 0.1, 'solver': 'lbfgs'}
Accuracy: 0.7910447761194029


## Decision Tree

In [133]:
param_dt = {
    'max_depth': [3, 5, 10],
    'min_samples_split': [2, 5, 10]
}

grid_dt = GridSearchCV(DecisionTreeClassifier(), param_dt, cv=5)
grid_dt.fit(X_train, Y_train)

print("Best Decision Tree:", grid_dt.best_params_)
print("Accuracy:", accuracy_score(Y_test, grid_dt.predict(X_test)))

Best Decision Tree: {'max_depth': 3, 'min_samples_split': 2}
Accuracy: 0.7985074626865671


## Random Forest

In [134]:
param_rf = {
    'n_estimators': [50, 100],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5]
}

grid_rf = GridSearchCV(RandomForestClassifier(), param_rf, cv=5)
grid_rf.fit(X_train, Y_train)

print("Best Random Forest:", grid_rf.best_params_)
print("Accuracy:", accuracy_score(Y_test, grid_rf.predict(X_test)))

Best Random Forest: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 50}
Accuracy: 0.8022388059701493


## Naive Bayes

In [135]:
grid_nb = GridSearchCV(GaussianNB(), param_grid={}, cv=5)
grid_nb.fit(X_train, Y_train)

print("Naive Bayes Accuracy:", accuracy_score(Y_test, grid_nb.predict(X_test)))

Naive Bayes Accuracy: 0.7910447761194029


## Support Vector Machine (SVM)

In [142]:
param_svm = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid_svm = GridSearchCV(SVC(), param_svm, cv=5)
grid_svm.fit(X_train, Y_train)

print("Best SVM:", grid_svm.best_params_)
print("Accuracy:", accuracy_score(Y_test, grid_svm.predict(X_test)))

Best SVM: {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
Accuracy: 0.7686567164179104


## K-Nearest Neighbors (KNN)

In [141]:
param_grid_knn = {
    'n_neighbors': list(range(1, 21)),
    'weights': ['uniform', 'distance']
}

# Initialize the model
knn = KNeighborsClassifier()

# GridSearchCV
grid_knn = GridSearchCV(knn, param_grid_knn, cv=5)
grid_knn.fit(X_train, Y_train)

# Results
print("Best parameters for KNN:", grid_knn.best_params_)
print("Best score for KNN:", grid_knn.best_score_)

Best parameters for KNN: {'n_neighbors': 13, 'weights': 'uniform'}
Best score for KNN: 0.7304


## Accuracy After GridSearchCV

In [149]:
print("Accuracy of Logistic Regression:", accuracy_score(Y_test, grid_logreg.predict(X_test)))
print("Accuracy of Decision Tree:", accuracy_score(Y_test, grid_dt.predict(X_test)))
print("Accuracy of Random Forest:", accuracy_score(Y_test, grid_rf.predict(X_test)))
print("Accuracy of Naive Bayes:", accuracy_score(Y_test, grid_nb.predict(X_test)))
print("Accuracy of SVM :", accuracy_score(Y_test, grid_svm.predict(X_test)))
print("Best score for KNN:", grid_knn.best_score_)

Accuracy of Logistic Regression: 0.7910447761194029
Accuracy of Decision Tree: 0.7985074626865671
Accuracy of Random Forest: 0.8022388059701493
Accuracy of Naive Bayes: 0.7910447761194029
Accuracy of SVM : 0.7686567164179104
Best score for KNN: 0.7304


## Random Forest show highest accuracy